name: Azure Static Web Apps CI/CD  
  
on:  
  push:  
    branches:  
      - master  
  pull_request:  
    types: [opened, synchronize, reopened, closed]  
    branches:  
      - master  
jobs:  
  main:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v3  
        with:  
          fetch-depth: 0 
      - name: Build and deploy 
        uses: nrwl/nx-set-shas@v3 
        with: 
         main-branch-name: 'master' 
      - run: npm ci  
      - run: npx nx affected --base=origin/master --head=${{ env.NX_HEAD }} --target=lint --parallel=3  
      - run: npx nx affected --base=origin/master --head=${{ env.NX_HEAD }} --target=test --parallel=3 --ci --code-coverage  
      - run: npx nx build shell  
      - uses: Azure/static-web-apps-deploy@v1  
        with:  
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_DUNE_0D16DFE00 }}  
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)  
          action: "upload"  
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######  
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig  
          app_location: "dist/apps/shell"  
          api_location: ""  
          output_location: "dist"  
          skip_app_build: true  
